name: main_deploy


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    - name: Build and Push Docker image to Docker hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: zguan0101/coastal_casa_finder
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: SSH to AWS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          echo "Connected to server successfully"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/coastal_casa_finder
          docker stop coastal_casa_finder
          docker rm coastal_casa_finder
          docker run -d -e db_pwd=${{ secrets.SERVER_DB_PASSWORD }} -p 8080:8080 --name coastal_casa_finder ${{ secrets.DOCKER_USERNAME }}/coastal_casa_finder
          docker image prune -a -f
          echo "All commands are done"

    - name: Send Slack Workflow Result
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: workflow-results
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_USERNAME: Github-Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
