name: main_deploy

on:
  push:
    branches:
      - main

jobs:
  build:
  env:
    REPO: coastal_casa_finder

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    - name: Build and Push Docker image to Docker hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: zguan0101/coastal_casa_finder
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: SSH to AWS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          echo "Connected to server successfully"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/$REPO
          docker stop $REPO
          docker rm $REPO
          docker run -d -p 8080:8080 --name $REPO ${{ secrets.DOCKER_USERNAME }}/$REPO
          echo "All commands are done"